# Generated by Django 4.1.7 on 2023-03-08 07:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cake_HouseDB', '0002_rename_student_client'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='gender',
            new_name='caketype',
        ),
        migrations.RemoveField(
            model_name='client',
            name='city',
        ),
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
        migrations.RemoveField(
            model_name='client',
            name='email',
        ),
        migrations.AddField(
            model_name='client',
            name='deliverydate',
            field=models.DateField(default=datetime.date(2023, 3, 8)),
        ),
        migrations.AddField(
            model_name='client',
            name='orderdate',
            field=models.DateField(default=datetime.date(2023, 3, 8)),
        ),
        migrations.AddField(
            model_name='client',
            name='price',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='client',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
